force-app/main/default/objects/Trivia__c/Trivia__c.object-meta.xml
<CustomObject>
    <label>Trivia</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Trivia Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trivia_Question__c/Trivia_Question__c.object-meta.xml
<CustomObject>
    <label>Trivia Question</label>
    <nameField>
        <displayFormat>TQ-{0000}</displayFormat>
        <label>Trivia Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trivia_Question__c/fields/Display_Value__c.field-meta.xml
<CustomField>
    <fullName>Display_Value__c</fullName>
    <label>Display Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trivia_Question__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trivia_Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trivia_Question__c/fields/Trivia__c.field-meta.xml
<CustomField>
    <fullName>Trivia__c</fullName>
    <label>Trivia</label>
    <referenceTo>Trivia__c</referenceTo>
    <relationshipLabel>Trivia Questions</relationshipLabel>
    <relationshipName>Trivia_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TriviaController.cls
public with sharing class TriviaController {
    
    @AuraEnabled
    public static List<Trivia_Question__c> getQuestions(String triviaId) {
        List<Trivia_Question__c> results = [SELECT Id, Name, Display_Value__c, Question_Text__c
                                            FROM Trivia_Question__c
                                            WHERE Trivia__c = :triviaId
                                            ORDER BY Order__c];
        return results;
    }
}